### ISSUE TITLE
ASAUIW to access PHP package to a MYMOID-GitHub repository (mymoid-php)

### ISSUE THREAD

**Issue by BeluMymoid** [mymoid/mymoid-php#1]
ASAUIW to access PHP package to a MYMOID-GitHub repository so that other developers can collaborate, make suggestions, and contribute to the development of the library.

## Scenarios: 
```
Given: Users access the PHP repository on GitHub (mymoid-php)
When: They navigate to the repository's main page.
Then: Clear indications are provided to distinguish between the two versions
```

## Technical task
- https://github.com/mymoid/mymoid-php/issues/2

## Acceptance Criteria:
- [x] Repository name is "mymoid-php"
- [x] Inside the PHP repository, both versions should be included (check @dhuertas-mymoid the best way to do this ).
- [x] A README.md file is included, describing the purpose of the library, how to install and use it, and any other relevant information for developers.

## Definition of Ready:

- [x] Acceptance criteria have been defined for the story.
- [x] Acceptance criteria are clear and understood by the whole team.
- [x] Story has been estimated and is within a certain size limit.
- [x] Story is clear and understood by the entire team.
- [x] UI designer has created mockups or fully designed screens for the story.
- [x] All dependencies, internal or external, have been resolved.

## Definition of Done:
- [x] All technical tasks are done.
- [x] All acceptance criteria are met.
- [x] Changes have been reviewed.
- [ ] CI tests have run successfully.
- [ ] Documentation has been updated.
- [ ] Release Notes have been updated.

**Comment by BeluMymoid** [comment]
ready to refine @dhuertas-mymoid

**Comment by dhuertas-mymoid** [comment]
@BeluMymoid is already available in the new repository https://github.com/mymoid/mymoid-php the main branch is for PHP 8 and with the `php-7 `branch you can use the other version of the SDK, the only repository that can use the packaging automatically (the name in PHP is `Composer`) it's the PHP 8 version that we are considering the main version, the other version it's only to compatibility with WordPress.

**Comment by BeluMymoid** [comment]
OK that's fine.
Ready to deploy 🚀
